#!/bin/bash

VM_NAME="arch-test-vm"
SNAPSHOT_NAME="clean-snapshot"
REPO_DIR="$(pwd)"
INSTALL_SCRIPT="install.sh"
VM_DIR="/ext/vm" # <---

BASE_MIRROR_URL="https://geo.mirror.pkgbuild.com/images/latest"
ARCH_QCOW2_FILENAME="Arch-Linux-x86_64-basic.qcow2"
ARCH_QCOW2_URL="$BASE_MIRROR_URL/$ARCH_QCOW2_FILENAME"
ARCH_QCOW2_SIG_FILENAME="$ARCH_QCOW2_FILENAME.sig"
ARCH_QCOW2_SIG_URL="$BASE_MIRROR_URL/$ARCH_QCOW2_SIG_FILENAME"
ARCH_QCOW2_SHA256SUM_FILENAME="$ARCH_QCOW2_FILENAME.SHA256"
ARCH_QCOW2_SHA256SUM_URL="$BASE_MIRROR_URL/$ARCH_QCOW2_SHA256SUM_FILENAME"
REPO_NAME="$( basename "$REPO_DIR" )"
